packaging_format = 2

id = "nodered"
name = "Node-RED"
description.en = "Flow-based programming for the Internet of Things"
description.fr = "Programmation par flux de données pour l'Internet des objets"

version = "3.1.0~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "Apache-2.0"
website = "https://nodered.org"
userdoc = "https://nodered.org/docs/"
code = "https://github.com/node-red/node-red"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/nodered"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/node-red/node-red/archive/refs/tags/3.1.0.tar.gz"
        sha256 = "dfb69f620085b4b84226bd1e270de3ad20597c985232fb723132929176c0baeb"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"
