#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "nodered"
name = "Node-RED"
description.en = "Flow-based programming for the Internet of Things"
description.fr = "Programmation par flux de données pour l'Internet des objets"

version = "3.1.5~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "Apache-2.0"
website = "https://nodered.org"
userdoc = "https://nodered.org/docs/"
code = "https://github.com/node-red/node-red"
cpe = "cpe:2.3:a:nodered:node-red"
fund = "https://openjsf.org"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "300M"
ram.runtime = "70M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/nodered"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    help.en = "Should the dashboard and HTTP endpoints be publicly accessible?"
    help.fr = "Le tableau de bord et les points d'accès HTTP doivent-ils être publiquement accessibles ?"
    type = "group"
    default = false

[resources]
    [resources.sources.main]
    url = "https://github.com/node-red/node-red/releases/download/3.1.5/node-red-3.1.5.zip"
    sha256 = "fae7500b0908833f8ad9c06d81b34c513b6ebd87f18d4a8ea993d62b971b94af"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "node-red-.*zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.additional_urls = ["/ui"]
    admin.url = "/admin"

    [resources.ports]
    main.default = 1880
