#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "nodered"
name = "Node-RED"
description.en = "Flow-based programming for the Internet of Things"
description.fr = "Programmation par flux de données pour l'Internet des objets"

version = "4.0.9~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "Apache-2.0"
website = "https://nodered.org"
userdoc = "https://nodered.org/docs/"
code = "https://github.com/node-red/node-red"
cpe = "cpe:2.3:a:nodered:node-red"
fund = "https://openjsf.org"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "300M"
ram.runtime = "70M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/nodered"

    [install.init_admin_permission]
    ask.en = "For example, to edit flows"
    ask.fr = "Par exemple, pour modifier les flux"
    type = "group"
    default = "admins"

    [install.init_main_permission]
    help.en = "This corresponds to access to the dashboard and HTTP endpoints"
    help.fr = "Ceci corresponds à l'accès au tableau de bord et aux points d'accès HTTP"
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/node-red/node-red/releases/download/4.0.9/node-red-4.0.9.zip"
    sha256 = "736d096cb8543a332ac75eee2e4f083b5203c17e7340448a7d02425b1e9c975a"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "node-red-.*zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.additional_urls = ["/ui"]
    admin.url = "/admin"

    [resources.ports]
    main.default = 1880
