packaging_format = 2

id = "nodered"
name = "Node-RED"
description.en = "Flow-based programming for the Internet of Things"
description.fr = "Programmation par flux de données pour l'Internet des objets"

version = "3.1.0~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "Apache-2.0"
website = "https://nodered.org"
userdoc = "https://nodered.org/docs/"
code = "https://github.com/node-red/node-red"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/nodered"

    [install.init_admin_permission]
    type = "group"
    default = "admins"
    ask.en = "Select the group which will be able to access the Node-RED Admin"
    help.en = "Select the group which will be able to access the Node-RED Admin to edit flows. It should *not* be Visitors."

    [install.init_ui_permission]
    type = "group"
    default = "admins"
    ask.en = "Who should have access to the Dashboard for this app?"
    help.en = "Select the group which will be able to access the Node-RED Dashboard. Be wary of which actions you expose if you choose Visitors."
   
    [install.init_main_permission]
    type = "group"
    default = "visitors"
    help.en = "Select the group which will be able to access the endpoints you create with the HTTP nodes. Be wary of which actions you expose if you choose Visitors."

[resources]
        [resources.sources.main]
        url = "https://github.com/node-red/node-red/archive/refs/tags/3.1.0.tar.gz"
        sha256 = "dfb69f620085b4b84226bd1e270de3ad20597c985232fb723132929176c0baeb"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    admin.url = "/admin"
    ui.url = "/ui"
    main.url = "/"
