packaging_format = 2

id = "nodered"
name = "Node-RED"
description.en = "Flow-based programming for the Internet of Things"
description.fr = "Programmation par flux de données pour l'Internet des objets"

version = "3.0.2~ynh3"

maintainers = ["tituspijean"]

[upstream]
license = "Apache-2.0"
website = "https://nodered.org"
userdoc = "https://nodered.org/docs/"
code = "https://github.com/node-red/node-red"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/nodered"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/node-red/node-red/releases/download/3.0.2/node-red-3.0.2.zip"
        sha256 = "6c452646648f9e86622148eff2208fb45d2311b5339481f86b445e9e2fa215c5"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
    admin.url="/admin"
