#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "nodered"
name = "Node-RED"
description.en = "Flow-based programming for the Internet of Things"
description.fr = "Programmation par flux de données pour l'Internet des objets"

version = "3.1.6~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "Apache-2.0"
website = "https://nodered.org"
userdoc = "https://nodered.org/docs/"
code = "https://github.com/node-red/node-red"
cpe = "cpe:2.3:a:nodered:node-red"
fund = "https://openjsf.org"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "300M"
ram.runtime = "70M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/nodered"

    [install.init_admin_permission]
    help.en = "Which group should be able to administer the app and edit flows?"
    help.fr = "Quel group devrait pouvoir adminstrer l'app et modifier des flux ?"
    type = "group"
    default = "admins"

    [install.init_main_permission]
    help.en = "Should the dashboard and HTTP endpoints be publicly accessible?"
    help.fr = "Le tableau de bord et les points d'accès HTTP doivent-ils être publiquement accessibles ?"
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/node-red/node-red/releases/download/3.1.6/node-red-3.1.6.zip"
    sha256 = "de5e120bc552093ceaf800601e0363d5429bf052e75eb9a1899bfb4d6dea4d1e"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "node-red-.*zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.additional_urls = ["/ui"]
    admin.url = "/admin"

    [resources.ports]
    main.default = 1880
