#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.9bcbf581a106d8514b61bd957d3705bee9d1548e.name = "Upgrade from 4.0.9~ynh1"

    #[default.test_upgrade_from.6eb3cdb]
    #name = "3.1.8~ynh1"
    #args.domain = "sub.domain.tld"
    #args.path = "/"
    #args.init_main_permission = "visitors"
    #args.init_admin_permission = "package_checker"
    #args.admin = "package_checker"
